Fix for #144
Change to correct use of pkgutil style namespace packages as documented https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages and illustrated in https://github.com/pypa/sample-namespace-packages/tree/master/pkgutil

Note: at the moment the `namespace_packages` directive is completely ignored, if you add the "luma" package to `packages` (in addition to `namespace_packages`) then `setup.py build` returns an error because it is expecting a pkg_resources style namespace package:

```
running build
running build_py
error: Namespace package problem: luma is a namespace package, but its
__init__.py does not call declare_namespace()! Please fix it.
(See the setuptools manual under "Namespace Packages" for details.)
```

Note: in the linked example the `find_packages()` method returns the "namespace" package as if it were an ordinary package.